# Generated by Django 5.2.4 on 2025-07-07 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('category', models.IntegerField(choices=[(0, 'Fruit'), (1, 'Vegetable'), (2, 'Starch'), (3, 'Dairy'), (4, 'Protein')], default=0)),
                ('min_age_months', models.IntegerField(default=0)),
                ('is_allergen', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
