# Generated by Django 5.2.4 on 2025-07-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_authorised',
            field=models.BooleanField(default=False),
        ),
    ]
