# Generated by Django 5.2.4 on 2025-07-15 16:47

import children.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthdate', models.DateField(validators=[children.models.validate_birthdate])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='profiles.profile')),
            ],
            options={
                'ordering': ['-birthdate'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
