# Generated by Django 5.2.4 on 2025-07-10 12:17

import children.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('profiles', '0002_rename_location_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birthdate',
            field=models.DateField(validators=[children.models.validate_birthdate]),
        ),
        migrations.AlterField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='profiles.profile'),
        ),
    ]
