# Generated by Django 5.2.4 on 2025-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_child_birthdate_alter_child_user'),
        ('profiles', '0002_rename_location_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='child',
            unique_together={('user', 'name')},
        ),
    ]
