# Generated by Django 5.2.4 on 2025-07-15 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(0, 'Purée'), (1, 'Mashed'), (2, 'Finger food'), (3, 'Liquid')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(0, 'Spoon Fed'), (1, 'Self Fed')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(0, 'Raw'), (1, 'Cooked')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(choices=[(0, 'Dislike'), (1, 'Indifferent'), (2, 'Like'), (3, 'Love')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('favourite', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('logged_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_logs', to='children.child')),
                ('consistency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_logs', to='logs.consistency')),
                ('feeding_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_logs', to='logs.feedingmethod')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_logs', to='foods.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_logs', to='logs.preparation')),
                ('satisfaction_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_logs', to='logs.satisfactionlevel')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
