# Generated by Django 5.2.4 on 2025-07-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='foods.food'),
        ),
    ]
